apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  namespace: dev
  labels:
    app: hello-kubernetes
  name: hello-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kubernetes
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - image: oadetiba/hello-kubernetes:latest
        name: hello-kubernetes
        resources: {}
status: {}
