apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: dev
  labels:
    app: hello-kubernetes
  name: hello-kubernetes
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
    nodePort: 30081
  selector:
    app: hello-kubernetes
status:
  loadBalancer: {}
